name: Sync RevSearchEngine folder to Appfolio Repo Backend folder

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger this workflow

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes RevSearchEngine folder to appfolio repo Backend folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.IBADRATHER_FULL_GITHUB_ACESS_PAT }}
      with:
        source_folder: 'RevSearchEngine'
        destination_repo: 'ibadrather/appfolio'
        destination_folder: 'Backend/RevSearchEngine'
        destination_branch: 'main'  # Add this line
        user_email: 'ibad.rather.ir@gmail.com'
        user_name: 'ibadrather'
        commit_msg: '[GHA] Sync RevSearchEngine to Backend'
